(function(){
const{calculateReadiness,buildPlanVariants,SPORT_LABELS,getResultCopy}=window.PlayReadyEngine;
const $=id=>document.getElementById(id);
const form=$("readinessForm");
const CHECKINS_KEY="playReadyCheckinsV2";
const SESSIONS_KEY="playReadySessionsV2";
const rangeIds=["fatigue","soreness","stress"];
let currentData=null,currentResult=null,currentPlans=[],selectedPlan=null;
let currentDemoName=null,playerStage=0,playerSeconds=0,playerRunning=false,playerInterval=null,currentWeekPlan=[],currentRecoveryActions=[];
const effortLabel=value=>value<=2?"Very easy":value<=4?"Easy":value<=5?"Moderate":value<=6?"Moderately hard":value<=8?"Hard":"Near maximum";

const PERSONAS={
  runner:{sport:"running",sleep:8,minutes:55,goal:"improve",fatigue:1,soreness:2,stress:1,trainedHardYesterday:false},
  lifter:{sport:"strength",sleep:5.5,minutes:45,goal:"maintain",fatigue:4,soreness:3,stress:4,trainedHardYesterday:true},
  cyclist:{sport:"cycling",sleep:7,minutes:60,goal:"recover",fatigue:3,soreness:5,stress:2,trainedHardYesterday:true}
};

rangeIds.forEach(id=>$(id).addEventListener("input",()=>{$(`${id}Value`).value=`${$(id).value} / 5`;}));
$("sessionRpe").addEventListener("input",()=>{const value=Number($("sessionRpe").value);$("sessionRpeValue").value=`${value} / 10 · ${effortLabel(value)}`;$("actualEffortDisplay").textContent=`${value}/10 · ${effortLabel(value)}`;});

function readForm(){return{sport:$("sport").value,sleep:Number($("sleep").value),minutes:Number($("minutes").value),goal:$("goal").value,fatigue:Number($("fatigue").value),soreness:Number($("soreness").value),stress:Number($("stress").value),trainedHardYesterday:$("trainedHardYesterday").checked,concerningSymptoms:$("concerningSymptoms").checked};}
function validate(data){if(!Number.isFinite(data.sleep)||data.sleep<0||data.sleep>14)return"Enter sleep between 0 and 14 hours.";if(!Number.isFinite(data.minutes)||data.minutes<15||data.minutes>180)return"Enter between 15 and 180 available minutes.";return"";}

form.addEventListener("submit",event=>{event.preventDefault();const data=readForm();const error=validate(data);$("formError").textContent=error;if(error)return;currentDemoName=null;showResult(data,true);});

function showResult(data,save){
  currentData=data;currentResult=calculateReadiness(data);currentPlans=buildPlanVariants(data,currentResult);selectedPlan=null;
  const copy=getResultCopy(currentResult.level);
  $("results").classList.toggle("safety-result",currentResult.safety);
  $("scoreValue").textContent=currentResult.score;$("scoreRing").style.setProperty("--score",currentResult.score);$("scoreRing").style.setProperty("--ring-color",currentResult.safety?"#e48b7e":currentResult.calculatedLevel==="recovery"?"#c8544d":currentResult.calculatedLevel==="low"?"#d9911e":"#16a36a");
  $("statusPill").textContent=copy.label;$("resultHeadline").textContent=copy.headline;$("resultSummary").textContent=copy.summary;
  const recommended=currentPlans[0];
  $("shareSummary").textContent=currentResult.safety?"PlayReady paused training guidance because a concerning symptom was reported.":`Readiness ${currentResult.score}/100 · ${copy.label} · ${recommended.total}-minute ${SPORT_LABELS[data.sport].toLowerCase()} session`;
  $("demoBanner").hidden=!currentDemoName;$("demoBannerText").textContent=currentDemoName?`${currentDemoName} · This example is not added to your personal history.`:"";
  renderFactors();renderPlans();initSimulator();renderWeeklyPlanner();renderRecoveryActions();resetWorkoutPlayer();$("feedbackForm").hidden=true;$("chosenPlan").hidden=true;$("copyStatus").textContent="";$("feedbackStatus").textContent="";$("saveFeedbackButton").disabled=false;
  $("results").hidden=false;
  if(save)saveCheckin({...data,score:currentResult.score,level:currentResult.level,breakdown:currentResult.breakdown,date:new Date().toISOString()});
  renderHistory();$("results").scrollIntoView({behavior:"smooth",block:"start"});
}

function renderFactors(){
  $("factorBars").innerHTML=currentResult.breakdown.map(item=>{const pct=item.max?Math.round(item.points/item.max*100):0;return`<div class="factor-row"><span>${item.key[0].toUpperCase()+item.key.slice(1)}</span><div class="factor-track" title="${item.label}"><div class="factor-fill" style="width:${pct}%"></div></div><b>${item.points?`-${item.points}`:"0"}</b></div>`;}).join("");
}

function renderPlans(){
  if(currentResult.safety){$("planOptions").innerHTML="";return;}
  $("planOptions").innerHTML=currentPlans.map(plan=>`<article class="plan-option" data-plan-card="${plan.id}"><div class="plan-option-head"><span>${plan.badge}</span><b>${plan.total} min</b></div><h3>${plan.title}</h3><div class="plan-meta">Target effort ${plan.targetEffort}/10 (${effortLabel(plan.targetEffort)}) · ${SPORT_LABELS[currentData.sport]}</div><ul class="mini-workout">${plan.segments.map(s=>`<li><b>${s.minutes}m</b><span>${s.title}</span></li>`).join("")}</ul><button class="select-plan" type="button" data-plan-id="${plan.id}">Choose this session</button></article>`).join("");
}

$("planOptions").addEventListener("click",event=>{const button=event.target.closest("[data-plan-id]");if(!button)return;selectedPlan=currentPlans.find(plan=>plan.id===button.dataset.planId);document.querySelectorAll("[data-plan-card]").forEach(card=>card.classList.toggle("selected",card.dataset.planCard===selectedPlan.id));document.querySelectorAll("[data-plan-id]").forEach(item=>item.textContent=item.dataset.planId===selectedPlan.id?"Selected":"Choose this session");$("chosenPlanText").textContent=`${selectedPlan.title} selected · ${selectedPlan.total} minutes · Target effort ${selectedPlan.targetEffort}/10`;$("chosenPlan").hidden=false;$("actualMinutes").value=selectedPlan.total;$("plannedEffortDisplay").textContent=`${selectedPlan.targetEffort}/10 · ${effortLabel(selectedPlan.targetEffort)}`;renderWeeklyPlanner();});

function initSimulator(){if(currentResult.safety)return;$("simSleep").value=currentData.sleep;$("simFatigue").value=currentData.fatigue;$("simSoreness").value=currentData.soreness;updateSimulator();}
function updateSimulator(){if(!currentData||currentResult.safety)return;const simulated={...currentData,sleep:Number($("simSleep").value),fatigue:Number($("simFatigue").value),soreness:Number($("simSoreness").value)};const result=calculateReadiness(simulated);const delta=result.score-currentResult.score;const copy=getResultCopy(result.level);$("simSleepValue").value=`${simulated.sleep}h`;$("simFatigueValue").value=`${simulated.fatigue}/5`;$("simSorenessValue").value=`${simulated.soreness}/5`;$("simulatedScore").textContent=result.score;$("simulatedDelta").textContent=delta===0?"No change":`${delta>0?"+":""}${delta} points`;$("simulatedStatus").textContent=copy.label;$("simulatedGuidance").textContent=copy.summary;}
["simSleep","simFatigue","simSoreness"].forEach(id=>$(id).addEventListener("input",updateSimulator));
$("resetSimulator").addEventListener("click",initSimulator);

$("copySummary").addEventListener("click",async()=>{const text=$("shareSummary").textContent;try{await navigator.clipboard.writeText(text);$("copyStatus").textContent="Copied to clipboard.";}catch{$("copyStatus").textContent="Copy unavailable here — select the summary text manually.";}});
$("completeSessionButton").addEventListener("click",startWorkoutPlayer);
$("feedbackForm").addEventListener("submit",event=>{event.preventDefault();if(!selectedPlan)return;const actualEffort=Number($("sessionRpe").value);const difference=actualEffort-selectedPlan.targetEffort;const session={date:new Date().toISOString(),sport:currentData.sport,plan:selectedPlan.title,plannedMinutes:selectedPlan.total,actualMinutes:Number($("actualMinutes").value),targetEffort:selectedPlan.targetEffort,rpe:actualEffort,feeling:$("postFeeling").value,readiness:currentResult.score};const items=getStorage(SESSIONS_KEY);items.push(session);setStorage(SESSIONS_KEY,items.slice(-20));const comparison=difference===0?"Actual effort matched the target.":difference>0?`Actual effort was ${difference} point${difference===1?"":"s"} harder than planned.`:`Actual effort was ${Math.abs(difference)} point${difference===-1?"":"s"} easier than planned.`;$("feedbackStatus").textContent=`Session saved. ${comparison}`;$("saveFeedbackButton").disabled=true;renderHistory();});

function formatTimer(seconds){const m=Math.floor(seconds/60).toString().padStart(2,"0");const s=(seconds%60).toString().padStart(2,"0");return`${m}:${s}`;}
function resetWorkoutPlayer(){clearInterval(playerInterval);playerInterval=null;playerRunning=false;playerStage=0;playerSeconds=0;$("workoutPlayer").hidden=true;$("playerTimer").textContent="00:00";$("playerPause").disabled=false;$("playerPause").textContent="Pause";$("playerNext").disabled=false;}
function startWorkoutPlayer(){if(!selectedPlan)return;resetWorkoutPlayer();$("workoutPlayer").hidden=false;$("playerPlanTitle").textContent=`${selectedPlan.title} · ${SPORT_LABELS[currentData.sport]}`;playerRunning=true;playerInterval=setInterval(()=>{if(playerRunning){playerSeconds++;$("playerTimer").textContent=formatTimer(playerSeconds);}},1000);renderPlayerStage();$("workoutPlayer").scrollIntoView({behavior:"smooth",block:"center"});}
function renderPlayerStage(){const segment=selectedPlan.segments[playerStage];if(!segment)return finishWorkout();$("playerStageNumber").textContent=`${playerStage+1} / ${selectedPlan.segments.length}`;$("playerStageTitle").textContent=segment.title;$("playerStageMeta").textContent=`Planned duration: ${segment.minutes} minutes · Target effort ${selectedPlan.targetEffort}/10 (${effortLabel(selectedPlan.targetEffort)}).`;$("playerProgressBar").style.width=`${playerStage/selectedPlan.segments.length*100}%`;$("playerNext").textContent=playerStage===selectedPlan.segments.length-1?"Finish workout →":"Complete stage →";}
function finishWorkout(){clearInterval(playerInterval);playerInterval=null;playerRunning=false;$("playerProgressBar").style.width="100%";$("playerStageNumber").textContent="Done";$("playerStageTitle").textContent="Session complete";$("playerStageMeta").textContent="Record how the workout felt to close the feedback loop.";$("playerPause").disabled=true;$("playerNext").disabled=true;$("feedbackForm").hidden=false;$("feedbackForm").scrollIntoView({behavior:"smooth",block:"center"});}
$("playerPause").addEventListener("click",()=>{playerRunning=!playerRunning;$("playerPause").textContent=playerRunning?"Pause":"Resume";});
$("playerNext").addEventListener("click",()=>{playerStage++;renderPlayerStage();});
$("playerExit").addEventListener("click",()=>{resetWorkoutPlayer();$("chosenPlan").scrollIntoView({behavior:"smooth",block:"center"});});

function renderWeeklyPlanner(){if(!currentData||currentResult.safety)return;const base=currentResult.calculatedLevel;const patterns=base==="ready"?["quality","easy","steady","recovery","quality","easy","rest"]:base==="moderate"?["steady","easy","recovery","steady","easy","quality","rest"]:["recovery","easy","rest","steady","recovery","easy","rest"];const label={quality:["Quality intention","Focused technique or controlled quality work",6,Math.max(35,currentData.minutes)],steady:["Steady intention","Build consistency at a sustainable pace",5,Math.max(30,Math.min(60,currentData.minutes))],easy:["Easy aerobic intention","Comfortable movement with plenty in reserve",3,30],recovery:["Recovery intention","Mobility, walking, or a very easy spin",2,20],rest:["Rest intention","Sleep, refuel, and let training adaptations settle",0,0]};const today=new Date();currentWeekPlan=patterns.map((type,index)=>{const date=new Date(today);date.setDate(today.getDate()+index);const item=label[type];return{type,index,date,title:index===0&&selectedPlan?selectedPlan.title:item[0],focus:item[1],effort:index===0&&selectedPlan?selectedPlan.targetEffort:item[2],duration:index===0&&selectedPlan?selectedPlan.total:item[3]};});$("weekGrid").innerHTML=currentWeekPlan.map(day=>`<button class="day-card ${day.index===0?"today":""} ${day.type==="rest"||day.type==="recovery"?"recovery-day":""}" type="button" data-day-index="${day.index}"><span class="day-name">${day.index===0?"Today":day.date.toLocaleDateString(undefined,{weekday:"short"})}</span><span class="day-icon">${day.index===0&&day.effort?`Today · ${day.effort}/10`:"Tentative"}</span><h3>${day.title}</h3><p>${day.focus}</p><small>${day.index===0?"Readiness-adjusted details →":"Check readiness that day →"}</small></button>`).join("");$("dayDetail").hidden=true;$("plannerNote").textContent="Only today's session is readiness-adjusted. Future cards are planning intentions, not predictions, and receive a final effort target after that morning's check-in.";}
$("weekGrid").addEventListener("click",event=>{const card=event.target.closest("[data-day-index]");if(!card)return;const day=currentWeekPlan[Number(card.dataset.dayIndex)];if(!day)return;$("dayDetailDate").textContent=day.index===0?"TODAY":day.date.toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"}).toUpperCase();$("dayDetailTitle").textContent=day.title;$("dayDetailEffort").textContent=day.index===0&&day.effort?`${day.effort}/10 · ${effortLabel(day.effort)}`:"Set after daily check-in";$("dayDetailFocus").textContent=day.type==="rest"?"Rest and recovery":day.focus;$("dayDetailDuration").textContent=day.index===0?(day.duration?`${day.duration} minutes`:"Rest day"):(day.duration?`Tentative · about ${day.duration} minutes`:"Tentative rest day");$("dayDetailDescription").textContent=day.index===0?"This is today's actionable recommendation, generated from today's readiness check-in.":"This is a planning intention, not a prediction of future readiness. Complete a new check-in that morning to confirm, reduce, replace, or skip the session.";$("dayDetail").hidden=false;$("dayDetail").scrollIntoView({behavior:"smooth",block:"nearest"});});
$("closeDayDetail").addEventListener("click",()=>{$("dayDetail").hidden=true;});

function recoveryActions(){const library={sleep:[["Earlier wind-down","Begin your bedtime routine 30 minutes earlier tonight."],["Protect the sleep window","Set a consistent lights-out time and reduce late interruptions."],["Morning light tomorrow","Get outdoor light after waking to support a steadier sleep rhythm."],["Late caffeine check","Avoid adding caffeine late in the day if it disrupts your sleep."]],soreness:[["8-minute mobility","Move gently through the areas reporting soreness."],["Longer warm-up","Add a gradual warm-up before deciding whether training feels appropriate."],["Easy range of motion","Use comfortable, pain-free movement instead of aggressive stretching."],["Recovery walk","Choose a short relaxed walk to keep movement light."]],fatigue:[["Reduce extra load","Keep optional training and errands easy today."],["Refuel after training","Pair fluids with a normal post-session meal."],["Short reset break","Take ten quiet minutes before the session and reassess energy."],["Trim one training block","Remove the least important part of today's session if energy stays low."]],stress:[["5-minute downshift","Try slow breathing or a quiet walk before the session."],["Screen-free reset","Create a short low-stimulation window before training."],["Simplify today's goal","Choose one clear purpose for the session instead of chasing every target."],["Calm cooldown","Finish with a few minutes of relaxed breathing and an easy walk."]]};const configs=[["sleep",currentData.sleep<7?"Based on low sleep":"Supports sleep consistency"],["soreness",currentData.soreness>=3?"Based on soreness":"Supports mobility"],["fatigue",currentData.fatigue>=3?"Based on fatigue":"Supports refueling"],["stress",currentData.stress>=3?"Based on stress":"Supports downshifting"]];const daySeed=Math.floor(Date.now()/86400000);return configs.map(([category,reason],index)=>({category,reason,choices:library[category],choiceIndex:(daySeed+index+Math.round(currentData[category]||currentData.sleep))%library[category].length,completed:false}));}
function renderRecoveryCards(){$("recoveryGrid").innerHTML=currentRecoveryActions.map((action,index)=>{const choice=action.choices[action.choiceIndex];return`<article class="recovery-action ${action.completed?"completed":""}" data-recovery-id="${index}"><button class="action-toggle" type="button" aria-label="Mark ${choice[0]} complete"><span class="action-check">✓</span><span class="action-reason">${action.reason}</span><h3>${choice[0]}</h3><p>${choice[1]}</p></button><button class="swap-action" type="button" data-swap-id="${index}">Swap suggestion</button></article>`;}).join("");updateRecoveryProgress();}
function renderRecoveryActions(){if(!currentData||currentResult.safety)return;currentRecoveryActions=recoveryActions();renderRecoveryCards();}
function updateRecoveryProgress(){const total=document.querySelectorAll(".recovery-action").length;const complete=document.querySelectorAll(".recovery-action.completed").length;$("recoveryCount").textContent=`${complete} / ${total}`;$("recoveryProgressBar").style.width=`${total?complete/total*100:0}%`;}
$("recoveryGrid").addEventListener("click",event=>{const swap=event.target.closest("[data-swap-id]");if(swap){const index=Number(swap.dataset.swapId);const action=currentRecoveryActions[index];action.choiceIndex=(action.choiceIndex+1)%action.choices.length;action.completed=false;renderRecoveryCards();return;}const toggle=event.target.closest(".action-toggle");if(!toggle)return;const index=Number(toggle.closest("[data-recovery-id]").dataset.recoveryId);currentRecoveryActions[index].completed=!currentRecoveryActions[index].completed;renderRecoveryCards();});

function getStorage(key){try{return JSON.parse(localStorage.getItem(key))||[];}catch{return[];}}
function setStorage(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{}}
function saveCheckin(record){const items=getStorage(CHECKINS_KEY);items.push(record);setStorage(CHECKINS_KEY,items.slice(-14));}
function dominantFactor(items){const totals={};items.forEach(item=>(item.breakdown||[]).forEach(f=>{totals[f.key]=(totals[f.key]||0)+f.points;}));const winner=Object.entries(totals).sort((a,b)=>b[1]-a[1])[0];return winner&&winner[1]>0?winner[0][0].toUpperCase()+winner[0].slice(1):"No clear limiter";}
function declining(items){if(items.length<3)return false;const last=items.slice(-3);return last[0].score>last[1].score&&last[1].score>last[2].score;}

function renderHistory(){
  const items=getStorage(CHECKINS_KEY),sessions=getStorage(SESSIONS_KEY);$("historySection").hidden=!items.length;if(!items.length)return;
  const avg=Math.round(items.reduce((sum,item)=>sum+item.score,0)/items.length);const completion=sessions.length?`${Math.round(sessions.filter(s=>s.actualMinutes>0).length/sessions.length*100)}%`:"No sessions yet";const weekAgo=Date.now()-7*86400000;const weeklyLoad=sessions.filter(s=>new Date(s.date).getTime()>=weekAgo).reduce((sum,s)=>sum+s.actualMinutes*s.rpe,0);
  $("insightGrid").innerHTML=`<article class="insight-card"><span>Average readiness</span><b>${avg}/100</b></article><article class="insight-card"><span>Most common limiter</span><b>${dominantFactor(items)}</b></article><article class="insight-card"><span>Session completion</span><b>${completion}</b></article><article class="insight-card"><span>7-day session load</span><b>${weeklyLoad} pts</b></article>${declining(items)?'<article class="insight-card alert"><span>Pattern detected</span><b>Readiness declined 3 check-ins in a row</b></article>':''}`;
  $("historyChart").innerHTML=items.slice(-7).map(item=>{const date=new Date(item.date).toLocaleDateString(undefined,{month:"short",day:"numeric"});return`<div class="history-bar"><i style="height:${Math.max(6,item.score)}%"><b>${item.score}</b></i><span>${date}</span></div>`;}).join("");
  $("sessionHistory").innerHTML=sessions.length?`<div class="card-heading"><span>Recent completed sessions</span><strong>${sessions.length} saved</strong></div>${sessions.slice(-3).reverse().map(s=>`<div class="session-row"><b>${SPORT_LABELS[s.sport]} · ${s.plan}</b><span>${s.actualMinutes} min · ${s.targetEffort?`Target ${s.targetEffort} → Actual ${s.rpe}/10`:`Actual effort ${s.rpe}/10`} · Felt ${s.feeling}</span></div>`).join("")}`:"";
}

function applyPersona(persona){const data=PERSONAS[persona];if(!data)return;Object.entries(data).forEach(([key,value])=>{const control=$(key);if(!control)return;if(control.type==="checkbox")control.checked=value;else control.value=value;});$("concerningSymptoms").checked=false;rangeIds.forEach(id=>$(id).dispatchEvent(new Event("input")));currentDemoName=persona==="runner"?"Well-rested runner":persona==="lifter"?"Tired strength athlete":"Sore cyclist";showResult(readForm(),false);}
document.querySelectorAll("[data-persona]").forEach(button=>button.addEventListener("click",()=>applyPersona(button.dataset.persona)));
$("demoButton").addEventListener("click",()=>applyPersona("lifter"));
$("editButton").addEventListener("click",()=>{$("check-in").scrollIntoView({behavior:"smooth"});});
$("clearHistory").addEventListener("click",()=>{localStorage.removeItem(CHECKINS_KEY);localStorage.removeItem(SESSIONS_KEY);renderHistory();});
renderHistory();
})();
